export const categories = [
    { value: 'toplivestreams', label: 'top livestreams' },
    { value: 'home', label: '🔌 Home' },
    { value: 'realitystars', label: 'TV Personalities' },
    { value: 'electronics', label: 'Electronics' },
    { value: 'fashionandbeauty', label: 'Fashion & Beauty' },
    { value: 'cooking', label: 'Cooking' },
    { value: 'fitness', label: 'Fitness' },
    { value: 'upcoming', label: 'Upcoming Streams' },
    { value: 'featured', label: 'Featured Creators' },
    { value: 'deals', label: 'Epic Daily Deals' },
    { value: 'gaming', label: 'Gaming' },
    { value: 'pets', label: 'Pets' },
    { value: 'health', label: 'Health & Wellness' },
    { value: 'food', label: 'Food' },
    { value: 'books', label: 'Books' },
{ value: 'baby', label: 'Baby' },
{ value: 'media', label: 'Media' },
{ value: 'everythingelse', label: 'Everything Else' },
];
